package com.dennisiluma.fashionartisan.enumclass

enum class StateSelectionEnumClass {
    LAGOS,ABUJA, ABIA,ADAMAWA,AKWAIBOM,ANAMBRA,BAUCHI,BAYELSA,BENUE,BORNO,CROSSRIVER,DELTA,EBONYI,EDO,EKITI,ENUGU,GOMBE,IMO,JIGAWA,KADUNA,KANO,KATSINA,KEBBI,KOGI,KWARA,NASARAWA,NIGER,OGUN,ONDO,OSUN,OYO,PLATEAU,RIVERS,SOKOTO,TARABA,YOBE,ZAMFARA,

}